# Generated by Django 4.2.7 on 2023-12-04 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0006_billing_ordered_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='product_name',
            field=models.CharField(default=' ', max_length=40),
        ),
        migrations.AddField(
            model_name='billing',
            name='product_quatity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='billing',
            name='sub_total',
            field=models.IntegerField(default=1),
        ),
    ]
