# Generated by Django 4.2.7 on 2023-12-05 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0007_billing_product_name_billing_product_quatity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='ordered_product',
        ),
    ]
