# Generated by Django 4.2.7 on 2023-12-05 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0008_remove_billing_ordered_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='product_quatity',
        ),
        migrations.CreateModel(
            name='Item_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finalapp.billing')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finalapp.product')),
            ],
        ),
    ]
