# Generated by Django 4.2.7 on 2023-12-06 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0011_alter_billing_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='country',
            field=models.CharField(default=' ', max_length=20),
        ),
    ]
