# Generated by Django 4.2.7 on 2023-12-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0012_alter_billing_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='address',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='billing',
            name='first_name',
            field=models.CharField(default=' ', max_length=30),
        ),
        migrations.AlterField(
            model_name='billing',
            name='last_name',
            field=models.CharField(default=' ', max_length=30),
        ),
        migrations.AlterField(
            model_name='billing',
            name='state',
            field=models.CharField(default=' ', max_length=20),
        ),
    ]
