# Generated by Django 4.2.7 on 2023-12-06 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0013_alter_billing_address_alter_billing_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='country',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
